//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Tasks = new HashSet<Task>();
            this.tbUsers = new HashSet<tbUser>();
        }
    
        public int employee_Id { get; set; }
        public string employee_Name { get; set; }
        public string employee_Address { get; set; }
        public string employee_PhoneNumber { get; set; }
        public string employee_Email { get; set; }
        public string employee_JoinDate { get; set; }
        public string employee_DateOfBirth { get; set; }
        public string employee_AuthenticationMode { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<tbUser> tbUsers { get; set; }
    }
}
