//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_Id { get; set; }
        public string task_Name { get; set; }
        public string task_Description { get; set; }
        public Nullable<System.DateTime> task_StartDate { get; set; }
        public Nullable<System.DateTime> task_EndDate { get; set; }
        public Nullable<int> task_Employee_Id { get; set; }
        public Nullable<int> task_Project_Id { get; set; }
        public Nullable<int> task_Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Project Project { get; set; }
    }
}
