//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int user_Id { get; set; }
        public Nullable<System.DateTime> user_CreatedDate { get; set; }
        public string user_Password { get; set; }
        public Nullable<int> user_employee_Id { get; set; }
        public string user_AuthenticationMode { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
